# SPDX-FileCopyrightText: 2025 Thomas Mathys
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "libshrinkler"
SPDX-PackageSupplier = "Thomas Mathys"
SPDX-PackageDownloadLocation = "https://github.com/tom42/libshrinkler"
annotations = []
