# SPDX-FileCopyrightText: 2025 Thomas Mathys
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["**/**"]
SPDX-FileCopyrightText = "Aske Simon Christensen"
SPDX-License-Identifier = "LicenseRef-Shrinkler"
